---
- name: Add repository
  shell:  |
    wget -q https://repos.influxdata.com/influxdata-archive_compat.key
    echo '393e8779c89ac8d958f81f942f9ad7fb82a25e133faddaf92e15b16e6ac9ce4c influxdata-archive_compat.key' | sha256sum -c && cat influxdata-archive_compat.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg > /dev/null
    echo 'deb [signed-by=/etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg] https://repos.influxdata.com/debian stable main' | sudo tee /etc/apt/sources.list.d/influxdata.list

- name: Install
  shell:  |
    apt-get update && apt-get install influxdb
    systemctl unmask influxdb.service
    systemctl start influxdb

- name: Add port
  shell:  |
    influx -port 5086
    systemctl restart influxdb

- name: Create llama database
  shell:  |
    Influx -port 5086
    systemctl restart influxdb