---
- name: Install GO
  ansible.builtin.apt:
    name: golang-go

- name: Clone
  ansible.builtin.git:
    repo: https://github.com/dropbox/llama
    dest: ./llama

- name: Build
  shell:  |
    cd llama
    GOOS=linux GOARCH=amd64 go build -o collector cmd/collector/main.go
    GOOS=linux GOARCH=amd64 go build -o reflector cmd/reflector/main.go
    GOOS=linux GOARCH=amd64 go build -o scraper cmd/scraper/main.go

- name: Install
  shell:  |
    cd llama
    mv collector /bin
    mv reflector /bin
    mv scraper /bin

- name: Create collector daemon
  template: src=collector.service.j2 dest=/lib/systemd/system/collector.service mode=644
  notify:
    - reload systemctl
#  systemd:
#    name: collector
#    state: started

- name: Create reflector daemon
  template: src=reflector.service.j2 dest=/lib/systemd/system/reflector.service mode=644
  notify:
    - reload systemctl
#  systemd:
#    name: reflector
#    state: started

- name: Create scraper daemon
  template: src=scraper.service.j2 dest=/lib/systemd/system/scraper.service mode=644
  notify:
    - reload systemctl
#  systemd:
#    name: scraper
#    state: started