---
- name: Install GO
  ansible.builtin.apt:
    name: golang-go

- name: Clone
  ansible.builtin.git:
    repo: https://github.com/dropbox/llama
    dest: ./llama

- name: Build
  shell:  |
    cd llama
    GOOS=linux GOARCH=amd64 go build -o scraper cmd/scraper/main.go

- name: Install
  shell:  |
    cd llama
    mv scraper /bin