---
- name: Update
  shell:  |
    apt-get update

- name: Install GO
  ansible.builtin.apt:
    name: golang-go

- name: Clone
  ansible.builtin.git:
    repo: https://github.com/dropbox/llama
    dest: ./llama

- name: Build
  shell:  |
    cd llama
    GOOS=linux GOARCH=amd64 go build -o collector cmd/collector/main.go
    GOOS=linux GOARCH=amd64 go build -o reflector cmd/reflector/main.go

- name: Install
  shell:  |
    cd llama
    mv collector /bin
    mv reflector /bin

- name: Create collector daemon
  template: src=collector.service.j2 dest=/lib/systemd/system/collector.service mode=644

- name: Start collector service
  systemd:
    name: collector
    state: started

- name: Create reflector daemon
  template: src=reflector.service.j2 dest=/lib/systemd/system/reflector.service mode=644

- name: Start reflector service
  systemd:
    name: reflector
    state: started